<a href="https://colab.research.google.com/github/miraculusik/tensorflow-deep-learning-practices/blob/main/Tensorflow_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 🛠 Exercises
 
**Q1 :** Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

**Q2 :** Find the shape, rank and size of the tensors you created in 1.

**Q3 :** Create two tensors containing random values between 0 and 1 with shape [5, 300].

**Q4 :** Multiply the two tensors you created in 3 using matrix multiplication.

**Q5 :** Multiply the two tensors you created in 3 using dot product.

**Q6 :** Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

**Q7 :** Find the min and max values of the tensor you created in 6.

**Q8 :** Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

**Q9 :** Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

**Q10 :** One-hot encode the tensor you created in 9.

In [2]:
import tensorflow as tf

## **Q1 :** 
Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [31]:
# scalar - 0 dimension
scalar_ = tf.constant(9.)
print(scalar_)
print("Dimension of 'scalar_':",scalar_.ndim)

tf.Tensor(9.0, shape=(), dtype=float32)
Dimension of 'scalar_': 0


In [32]:
# vector - 1 dimension
vector_ = tf.constant([1,3,5,7,9.])
print(vector_)
print("Dimension of 'vector_':",vector_.ndim)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)
Dimension of 'vector_': 1


In [33]:
# matrix - 2 imension
matrix_ = tf.constant([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.]])
print(matrix_)
print("Dimension of 'matrix_':",matrix_.ndim)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)
Dimension of 'matrix_': 2


In [34]:
# tensor - more than 2 dimension (in this example i used rank 3 tensor)
tensor_ = tf.constant([[[1.,2.,3.],
                        [4.,5.,6.]],
                       [[7.,8.,9.],
                        [10.,11.,12.]]])

print(tensor_)
print("Dimension of 'tensor_':",tensor_.ndim)

tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)
Dimension of 'tensor_': 3


In [22]:
tensor_

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float32)>

## **Q2 :** 

Find the shape, rank and size of the tensors you created in 1.

In [39]:
print("shape of 'tensor_':",tensor_.shape)

shape of 'tensor_': (2, 2, 3)


In [38]:
print("rank of 'tensor_':",tensor_.ndim)

rank of 'tensor_': 3


In [43]:
print("size of 'tensor_':",tf.size(tensor_).numpy())

size of 'tensor_': 12


## **Q3 :** 

Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [45]:
tf.random.set_seed(42)
tensor_1 = tf.random.uniform(shape=(5,300), maxval=1)

In [49]:
tf.random.set_seed(9)
tensor_2 = tf.random.uniform(shape=(5,300), maxval=1)

In [50]:
tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [51]:
tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.46696687, 0.7581432 , 0.6996453 , ..., 0.27514398, 0.35320437,
        0.83345044],
       [0.41634333, 0.23471797, 0.14901066, ..., 0.6938119 , 0.7583524 ,
        0.9539218 ],
       [0.18273306, 0.13849425, 0.12764347, ..., 0.15002131, 0.76074624,
        0.8743453 ],
       [0.36680603, 0.7209959 , 0.25549746, ..., 0.85957277, 0.45394373,
        0.49012446],
       [0.39641595, 0.533947  , 0.12242699, ..., 0.6687479 , 0.710225  ,
        0.8829614 ]], dtype=float32)>

## **Q4 :** 

Multiply the two tensors you created in 3 using matrix multiplication.

In [53]:
tensor_3 = tf.matmul(tensor_1, tensor_2, transpose_b=True)
tensor_3

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.10428 , 77.224945, 75.82192 , 72.84037 , 78.41609 ],
       [68.418564, 70.82692 , 67.723526, 68.2842  , 73.798874],
       [73.38815 , 75.47829 , 70.3624  , 74.29562 , 74.817055],
       [72.03658 , 72.94582 , 70.96188 , 73.10724 , 73.52516 ],
       [75.182175, 76.07675 , 74.27774 , 73.76506 , 79.25421 ]],
      dtype=float32)>

## **Q5 :** 

Multiply the two tensors you created in 3 using dot product.


In [59]:
tensor_4 = tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)
tensor_4

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.10428 , 77.224945, 75.82192 , 72.84037 , 78.41609 ],
       [68.418564, 70.82692 , 67.723526, 68.2842  , 73.798874],
       [73.38815 , 75.47829 , 70.3624  , 74.29562 , 74.817055],
       [72.03658 , 72.94582 , 70.96188 , 73.10724 , 73.52516 ],
       [75.182175, 76.07675 , 74.27774 , 73.76506 , 79.25421 ]],
      dtype=float32)>

## **Q6 :** 

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [68]:
tensor_q6 = tf.random.Generator.from_seed(9)
tensor_q6 = tf.random.uniform(shape=(224, 224, 3))
tensor_q6

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.46925545, 0.8339242 , 0.55883753],
        [0.9587674 , 0.57460964, 0.8234668 ],
        [0.90690315, 0.95474184, 0.45882404],
        ...,
        [0.03103888, 0.65403974, 0.4118452 ],
        [0.05530989, 0.91565394, 0.3315115 ],
        [0.2680905 , 0.14662123, 0.52433586]],

       [[0.3360393 , 0.27864778, 0.4258324 ],
        [0.58998096, 0.17216122, 0.05244625],
        [0.19852293, 0.57282495, 0.16788399],
        ...,
        [0.75059557, 0.8777534 , 0.01715028],
        [0.48205316, 0.8545188 , 0.47807848],
        [0.857443  , 0.4881196 , 0.8788835 ]],

       [[0.00928235, 0.475919  , 0.37370384],
        [0.3702476 , 0.13182461, 0.8551451 ],
        [0.15644193, 0.00772548, 0.1700393 ],
        ...,
        [0.9340694 , 0.688807  , 0.8853426 ],
        [0.9888463 , 0.02068186, 0.00575805],
        [0.59455884, 0.44837892, 0.28249753]],

       ...,

       [[0.6280961 , 0.04600716, 0.3046044 ],
        [0.71

## **Q7 :** 

Find the min and max values of the tensor you created in 6.

In [70]:
tf.reduce_max(tensor_q6)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999944>

In [72]:
tf.reduce_min(tensor_q6)

<tf.Tensor: shape=(), dtype=float32, numpy=3.33786e-06>

## **Q8 :** 

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [75]:
tensor_q8 = tf.random.Generator.from_seed(1)
tensor_q8 = tf.random.uniform(shape=(1, 224, 224, 3))
tensor_q8.shape

TensorShape([1, 224, 224, 3])

In [77]:
tensor_q8_squeeze = tf.squeeze(tensor_q8)
tensor_q8_squeeze.shape

TensorShape([224, 224, 3])

## **Q9 :** 

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [87]:
tensor_q9 = tf.constant([6, 3, 5, 4, 2, 1, 9, 7, 8, 0])
tensor_q9

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 3, 5, 4, 2, 1, 9, 7, 8, 0], dtype=int32)>

In [88]:
tf.argmax(tensor_q9)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [89]:
tf.argmin(tensor_q9)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

## **Q10 :** 

One-hot encode the tensor you created in 9.

In [94]:
tf.one_hot(tf.sort(tensor_q9), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>